#serirs

In [ ]:
#series是pandas中的一种数据结构，类似于一维数组，可以存储各种数据类型，并且具有索引。它可以通过列表、数组、字典等方式创建，并且支持各种操作，如切片、过滤、统计等。
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)
#自定义索引
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])#index参数用于指定索引标签，可以是列表、数组等类型。默认情况下，索引标签为整数，从0开始递增。
print(s)
#定义name属性
s.name='my_series'#name属性用于给Series对象命名，可以是任意字符串
print(s)

In [ ]:
s1=pd.Series(s,index=['a','b','c'])#通过index参数指定索引标签，可以选择性地提取数据
print(s1)

series的属性
index索引对象
values值
dtype元素类型
name名称
size元素个数
shape形状
ndim维度
loc[]显示索引，按标签索引或切片
iloc[]隐式索引，按位置索引或切片
at[]使用标签访问单个元素
iat[]使用位置访问单个元素

In [ ]:
print(s.values)

In [17]:
population_dict={'bj':3000,'sh':2000,'sz':3200}
area_dict={'bj':300,'sh':100,'sz':150}
temp=pd.DataFrame({'population':population_dict,'area':area_dict})
print(temp)

    population  area
bj        3000   300
sh        2000   100
sz        3200   150

In [ ]:
temp.index
temp.values
temp.columns

In [ ]:
#读取excel文件
import pandas as pd
data=pd.read_excel('douyin_video_data.xlsx')#需要安装openpyxl库
print(data)

In [ ]:
pd.set_option('display.max_rows',10)#设置显示的最大行数为10，超过10行的数据将被省略显示
print(data)

In [ ]:
data2=pd.read_excel('douyin_video_data.xlsx',usecols=[0,1,3,5,6])#读取指定工作表的数据    usecols参数用于指定要读取的列，可以是列的索引（从0开始）或列的名称
print(data2)

In [ ]:
#指定工作表
data3=pd.read_excel('douyin_video_data.xlsx',sheet_name='Sheet1')#sheet_name参数用于指定要读取的工作表，可以是工作表的名称或索引（从0开始）
print(data3)

In [ ]:
df1=pd.read_csv(r'D:\数据表\tiktok_dataset.csv',encoding='utf-8')#读取csv文件，encoding参数用于指定文件的编码格式，默认为utf-8
print(df1)

In [ ]:
df2=pd.read_table('',sep=',',encoding='gbk')#读取文本文件，sep参数用于指定分隔符，默认为制表符\t

In [39]:
mysql_sentence='SELECT * FROM table_name'
connection=pysql.connect(host='localhost,db='database_name',user='username',password='password')#连接数据库，host参数用于指定数据库服务器的地址，db参数用于指定要连接的数据库名称，user参数用于指定数据库用户名，password参数用于指定数据库密码
df3=pd.read_sql(mysql_sentence,con=connection) #读取数据库，con参数用于指定数据库连接对象

SyntaxError: unterminated string literal (detected at line 2) (660487126.py, line 2)

In [1]:
import pymysql as pysql
import  pandas as pd
mysql_sentence1='select *,cast(isdelete as unsigned) as isdelete_int from db_students  where age>20;'
connection1=pysql.connect(host='localhost',database='libing',user='root',password='123456')
df4=pd.read_sql(mysql_sentence1,con=connection1)#usecols参数用于指定要读取的列，可以是列的索引（从0开始）或列的名称
print(df4)

   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0

C:\Users\libing\AppData\Local\Temp\ipykernel_56156\3391649997.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df4=pd.read_sql(mysql_sentence1,con=connection1)#usecols参数用于指定要读取的列，可以是列的索引（从0开始）或列的名称

In [32]:
#保存到外部文件
df4.to_csv(r'd:/数据表/students.csv',sep=',',columns=['id','name','age','isdelete_int'],index=False,encoding='utf-8')#to_csv方法用于将DataFrame对象保存为CSV文件，sep参数用于指定分隔符，columns参数用于指定要保存的列，index参数用于指定是否保存索引，encoding参数用于指定文件的编码格式
df4.to_excel(r'd:/数据表/students.xlsx',sheet_name='students',index=False,encoding='gbk')#to_excel方法用于将DataFrame对象保存为Excel文件，sheet_name参数用于指定工作表名称，index参数用于指定是否保存索引，encoding参数用于指定文件的编码格式

In [36]:
#保存到数据库
from sqlalchemy import create_engine
engine=create_engine('mysql+pymysql://root:123456@localhost/libing')#create_engine函数用于创建数据库引擎，参数格式为'mysql+pymysql://username:password@host/database_name'
df4.to_sql('students_table',con=engine,if_exists='fail',index=False)#to_sql方法用于将DataFrame对象保存到数据库表中，name参数用于指定表名，con参数用于指定数据库连接对象，if_exists参数用于指定如果表已经存在时的处理方式，index参数用于指定是否保存索引

ValueError: Table 'students_table' already exists.

In [41]:
#了解数据
print(df4.head())#head方法用于显示DataFrame对象的前几行数据，默认为5行
print(df4.tail())#tail方法用于显示DataFrame对象的后几行数据，默认为5行
print(df4.info())#info方法用于显示DataFrame对象的基本信息，包括数据类型、非空值数量等
print(df4.describe())#describe方法用于显示DataFrame对象的统计信息，包括计数、均值、标准差、最小值、25%分位数、50%分位数、75%分位数和最大值等

   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
   id  age   sid sex          name isdelete  isdelete_int
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            9 non-null      int64
 1   age           9 non-null      int64
 2   sid           9 non-null      str
 3   sex           9 non-null      str
 4   name          9 non-null      str
 5   isdelete      9 non-null      object
 6   isdelete_int  9 non-null      int64
dtypes: int64(3), object(1), str(3)
memory usage: 765.0+ bytes
None
              id        age  isdelete_int
count   9.000000   9.000000           9.0
mean    7.888889  34.444444           0.0
std     2.934469  13.172994           0.0
min     3.000000  22.000000           0.0
25%     6.000000  23.000000           0.0
50%     8.000000  30.000000           0.0
75%    10.000000  40.000000           0.0
max    12.000000  60.000000           0.0

In [3]:
#列的操作
#修改列名
df4.rename(columns={'sex1':'sex'})

   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0

In [11]:
#增加列
df4['new_col']=range(9)#通过赋值的方式增加新列，列名为'new_col'，值为一个范围从0到DataFrame对象行数的整数序列
print(df4)

   id  age   sid sex          name isdelete  isdelete_int  new_col
0   3   23  0003   1       daolang  b'\x00'             0        0
1   5   30  0005   1   zhangxueyou  b'\x00'             0        1
2   6   32  0006   1  zhangguorong  b'\x00'             0        2
3   7   22  0007   0     liruotong  b'\x00'             0        3
4   8   40  0008   1  zhongmingqiu  b'\x00'             0        4
5   9   50  0009   1   zhouxingchi  b'\x00'             0        5
6  10   30  0010   1     zhazhahui  b'\x00'             0        6
7  11   60  0011   1     renxianqi  b'\x00'             0        7
8  12   23    12   0            李四  b'\x00'             0        8

In [13]:
df4.apply(lambda x:x*2,axis=0)#apply方法用于对DataFrame对象的行或列应用函数，lambda函数用于定义一个匿名函数，这里对每个元素乘以2，axis参数用于指定应用函数的轴，0表示按列应用，1表示按行应用
df4['age'].apply(lambda x:x*2)#对指定列的每个元素应用函数，这里对'age'列的每个元素乘以2

0     46
1     60
2     64
3     44
4     80
5    100
6     60
7    120
8     46
Name: age, dtype: int64

In [ ]:
df4.insert(2,'new_col',insert_col)#insert方法用于在DataFrame对象中插入新列，参数分别为插入位置的索引、列名和列

In [14]:
#删除列
df4.drop(columns=['new_col'],inplace=True)#drop方法用于删除DataFrame对象的列，columns参数用于指定要删除的列，inplace参数用于指定是否在原DataFrame对象上进行修改，默认为False
print(df4)

   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0

In [15]:
#数据类型转换
df4['age']=df4['age'].astype(float)#astype方法用于转换数据类型，这里将'age'列的数据类型转换为float
print(df4.dtypes)

id                int64
age             float64
sid                 str
sex                 str
name                str
isdelete         object
isdelete_int      int64
dtype: object

In [16]:
#索引的操作
#设置索引
df4.set_index('id',inplace=True)#set_index方法用于设置DataFrame对象的索引，参数为要设置为索引的列名，inplace参数用于指定是否在原DataFrame对象上进行修改，默认为False
print(df4)
#重置索引
df4.reset_index(inplace=True)#reset_index方法用于重置DataFrame对象的索引，参数inplace用于指定是否在原DataFrame对象上进行修改，默认为False

     age   sid sex          name isdelete  isdelete_int
id
3   23.0  0003   1       daolang  b'\x00'             0
5   30.0  0005   1   zhangxueyou  b'\x00'             0
6   32.0  0006   1  zhangguorong  b'\x00'             0
7   22.0  0007   0     liruotong  b'\x00'             0
8   40.0  0008   1  zhongmingqiu  b'\x00'             0
9   50.0  0009   1   zhouxingchi  b'\x00'             0
10  30.0  0010   1     zhazhahui  b'\x00'             0
11  60.0  0011   1     renxianqi  b'\x00'             0
12  23.0    12   0            李四  b'\x00'             0

In [18]:
#dataframe的索引和切片
#df[]索引
print(df4['name'])#通过列名索引获取指定列的数据，这里获取'name'列的数据
print(df4[['name','age']])#通过列名索引获取多个列的数据，这里获取'name'和'age'列的数据
#loc和iloc的区别
#loc是基于标签的索引，iloc是基于位置的索引
print(df4.loc[0])#loc方法用于基于标签进行索引，这里获取索引标签为0的行数据
print(df4.iloc[0])#iloc方法用于基于位置进行索引，这里获取位置索引为0的行数据
#切片
print(df4.loc[0:2])#loc方法用于基于标签进行切片，这里获取索引标签从0到2的行数据，包含2
print(df4.iloc[0:2])#iloc方法用于基于位置进行切片，这里获取位置索引从0到2的行数据，不包含2

0         daolang
1     zhangxueyou
2    zhangguorong
3       liruotong
4    zhongmingqiu
5     zhouxingchi
6       zhazhahui
7       renxianqi
8              李四
Name: name, dtype: str
           name   age
0       daolang  23.0
1   zhangxueyou  30.0
2  zhangguorong  32.0
3     liruotong  22.0
4  zhongmingqiu  40.0
5   zhouxingchi  50.0
6     zhazhahui  30.0
7     renxianqi  60.0
8            李四  23.0
id                    3
age                23.0
sid                0003
sex                   1
name            daolang
isdelete        b'\x00'
isdelete_int          0
Name: 0, dtype: object
id                    3
age                23.0
sid                0003
sex                   1
name            daolang
isdelete        b'\x00'
isdelete_int          0
Name: 0, dtype: object
   id   age   sid sex          name isdelete  isdelete_int
0   3  23.0  0003   1       daolang  b'\x00'             0
1   5  30.0  0005   1   zhangxueyou  b'\x00'             0
2   6  32.0  0006   1  zhangguorong  b'\x00'             0
   id   age   sid sex         name isdelete  isdelete_int
0   3  23.0  0003   1      daolang  b'\x00'             0
1   5  30.0  0005   1  zhangxueyou  b'\x00'             0

In [2]:
#isin方法用于判断DataFrame对象中的元素是否在指定的列表或数组中，返回一个布尔型的DataFrame对象
print(df4['name'].isin(['Alice','Bob']))#判断'name'列中的元素是否在列表['Alice','Bob']中，返回一个布尔型的Series对象
print(df4[df4['name'].isin(['Alice','Bob'])])#通过布尔索引获取'name'列中元素在列表['Alice','Bob']中的行数据

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: name, dtype: bool
Empty DataFrame
Columns: [id, age, sid, sex, name, isdelete, isdelete_int]
Index: []

In [4]:
#条件筛选
print(df4[df4['age']>20])#通过条件筛选获取'age'列中元素大于20的行数据
print(df4[(df4['age']>20) & (df4['sex']=='1')])#通过条件筛选获取'age'列中元素大于20且'sex'列中元素为'F'的行数据

   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0
   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0

In [5]:
df4.query('age>20 and sex=="1"')#query方法用于通过查询表达式进行条件筛选，这里获取'age'列中元素大于20且'sex 列中元素为'F'的行数据，查询表达式中的列名需要用引号括起来，字符串值需要用双引号括起来

   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0

In [7]:
#排序
print(df4.sort_values(by='age'))#sort_values方法用于根据指定列的值进行排序，by参数用于指定排序的列名，默认为升序排序
print(df4.sort_values(by='age',ascending=False))#通过设置ascending参数为False进行降序排序

   id  age   sid sex          name isdelete  isdelete_int
3   7   22  0007   0     liruotong  b'\x00'             0
0   3   23  0003   1       daolang  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
   id  age   sid sex          name isdelete  isdelete_int
7  11   60  0011   1     renxianqi  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
0   3   23  0003   1       daolang  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0

In [6]:
df4.sort_index(inplace=False)#sort_index方法用于根据索引进行排序，inplace参数用于指定是否在原DataFrame对象上进行修改，默认为False
print(df4)

   id  age   sid sex          name isdelete  isdelete_int
0   3   23  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0

In [ ]:
#统计分析
print(df4['age'].mean())#mean方法用于计算指定列的平均值，这里计算'age'列的平均值
print(df4['age'].median())#median方法用于计算指定列的中位数，这里计算'age'列的中位数
print(df4['age'].std())#std方法用于计算指定列的标准差，这里计算'age'列的标准差
print(df4['age'].min())#min方法用于计算指定列的最小值，这里计算'age'列的最小值
print(df4['age'].max())#max方法用于计算指定列的最大值，这里计算'age'列的最大值
print(df4['age'].count())#count方法用于计算指定列的非空值数量，这里计算'age'列的非空值数量
print(df4['age'].value_counts())#value_counts方法用于计算指定列中每个唯一值的出现次数，这里计算'age'列中每个唯一值的出现次数
print(df4['age'].unique())#unique方法用于获取指定列中的唯一值，这里获取'age'列中的唯一值

In [9]:
#修改数据
df4.loc[0,'age']=25#通过loc方法修改指定行列的数据，这里将索引标签为0的行的'age'列的值修改为25
print(df4)
df4.replace({'age':{25:30}},inplace=True)#replace方法用于替换DataFrame对象中的指定值，这里将'age'列中值为25的元素替换为30，inplace参数用于指定是否在原DataFrame对象上进行修改，默认为False
print(df4)

   id  age   sid sex          name isdelete  isdelete_int
0   3   25  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0
   id  age   sid sex          name isdelete  isdelete_int
0   3   30  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   32  0006   1  zhangguorong  b'\x00'             0
3   7   22  0007   0     liruotong  b'\x00'             0
4   8   40  0008   1  zhongmingqiu  b'\x00'             0
5   9   50  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   60  0011   1     renxianqi  b'\x00'             0
8  12   23    12   0            李四  b'\x00'             0

In [10]:
#条件筛选替换
df4.loc[df4['age']>20,'age']=30#通过条件筛选替换DataFrame对象中的指定值，这里将'age'列中大于20的元素替换为30
print(df4)

   id  age   sid sex          name isdelete  isdelete_int
0   3   30  0003   1       daolang  b'\x00'             0
1   5   30  0005   1   zhangxueyou  b'\x00'             0
2   6   30  0006   1  zhangguorong  b'\x00'             0
3   7   30  0007   0     liruotong  b'\x00'             0
4   8   30  0008   1  zhongmingqiu  b'\x00'             0
5   9   30  0009   1   zhouxingchi  b'\x00'             0
6  10   30  0010   1     zhazhahui  b'\x00'             0
7  11   30  0011   1     renxianqi  b'\x00'             0
8  12   30    12   0            李四  b'\x00'             0

In [13]:
from sqlalchemy import create_engine
engine=create_engine('mysql+pymysql://root:123456@localhost/libing')#create_engine函数用于创建数据库引擎，参数格式为'mysql+pymysql://username:password@host/database_name'
df4.to_sql('students_table',con=engine,if_exists='replace',index=False)#to_sql方法用于将DataFrame对象保存到数据库表中，name参数用于指定表名，con参数用于指定数据库连接对象，if_exists参数用于指定如果表已经存在时的处理方式，这里设置为'replace'表示替换原有表，index参数用于指定是否保存索引

9

In [17]:
import pandas as pd
data4=pd.DataFrame({'sex':['男','女','男','女'],'age':[20,25,30,35]})
data4.head
pd.get_dummies(data4,columns=['sex'])#get_dummies方法用于将分类变量转换为虚拟变量，这里将'sex'列中的分类变量转换为虚拟变量，columns参数用于指定要转换的列名
pd.get_dummies(data4,columns=['sex'],drop_first=True)#通过设置drop_first参数为True来避免虚拟变量陷阱，即删除第一个虚拟变量列

   age  sex_男
0   20   True
1   25  False
2   30   True
3   35  False

In [18]:
#数据分箱
table=pd.DataFrame({'age':[20,25,30,35,40]})
bins=[0,20,30,40]#定义分箱的边界，这里将年龄分为三个箱子：0-20岁、20-30岁、30-40岁
labels=['0-20','20-30','30-40']#定义分箱的标签，这里分别为'0-20'、'20-30'、'30-40'
table['age_group']=pd.cut(table['age'],bins=bins,labels=labels,include_lowest=True)#cut方法用于将连续变量分箱，参数分别为要分箱的列、分箱的边界、分箱的标签和是否包含边界值，这里将'age'列进行分箱，分箱的边界为bins，分箱的标签为labels，include_lowest参数设置为True表示包含最小边界值
print(table)

   age age_group
0   20      0-20
1   25     20-30
2   30     20-30
3   35     30-40
4   40     30-40

In [31]:
#数据分组
data5=pd.DataFrame({'sex':['男','女','男','女'],'age':[20,25,30,35],'height':[170,160,180,165],'是否婚配':[1,1,0,0]})
grouped=data5.groupby(['sex','是否婚配'])#groupby方法用于将DataFrame对象按照指定列进行分组，这里按照'sex'列进行分组，返回一个GroupBy对象
grouped.mean()#对分组后的数据进行聚合操作，这里计算每个性别组的平均年龄和平均身高

           age  height
sex 是否婚配
女   0     35.0   165.0
    1     25.0   160.0
男   0     30.0   180.0
    1     20.0   170.0

In [47]:
#数据透视表
data6=pd.DataFrame({'sex':['男','女','男','女'],'age':[20,25,30,35],'height':[170,160,180,165],'是否婚配':[1,1,0,0]})
pivot_table=data6.pivot_table(values='age',index='sex',columns='是否婚配',aggfunc='mean')#pivot_table方法用于创建数据透视表，参数分别为要聚合的列、行索引、列索引和聚合函数，这里将'age'列进行聚合，行索引为'sex'列，列索引为'是否婚配'列，聚合函数为'mean'表示计算平均值
pivot_table

是否婚配     0     1
sex
女     35.0  25.0
男     30.0  20.0

In [45]:
data6.agg({'age':'max','height':'max'})#agg方法用于对DataFrame对象的列进行聚合操作，参数为一个字典，键为列名，值为聚合函数，这里计算'age'列和'height'列的最大值

age        35
height    180
dtype: int64

In [50]:
a=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
a.unstack()#unstack方法用于将Series对象的行转换为列，返回

A  0    1
   1    2
   2    3
B  0    4
   1    5
   2    6
dtype: int64

In [49]:
a.stack()#stack方法用于将DataFrame对象的列转换为行，返回一个Series对象

0  A    1
   B    4
1  A    2
   B    5
2  A    3
   B    6
dtype: int64

In [51]:
a.T

   0  1  2
A  1  2  3
B  4  5  6

In [52]:
#数据合并
df1=pd.DataFrame({'id':[1,2,3],'name':['Alice','Bob','Charlie']})
df2=pd.DataFrame({'id':[1,2,4],'age':[20,25,30]})
merged=pd.merge(df1,df2,on='id',how='inner')#merge方法用于合并两个DataFrame对象，参数分别为要合并的DataFrame对象、连接键和连接方式，这里通过'id'列进行连接，连接方式为'inner'表示取交集
print(merged)
merged=pd.merge(df1,df2,on='id',how='outer')#通过设置how参数为'outer'表示取并集
print(merged)
merged=pd.merge(df1,df2,on='id',how='left')#通过设置how参数为'left'表示取左表的所有数据
print(merged)
merged=pd.merge(df1,df2,on='id',how='right')#通过设置how参数为'right'表示取右表的所有数据
print(merged)

   id   name  age
0   1  Alice   20
1   2    Bob   25
   id     name   age
0   1    Alice  20.0
1   2      Bob  25.0
2   3  Charlie   NaN
3   4      NaN  30.0
   id     name   age
0   1    Alice  20.0
1   2      Bob  25.0
2   3  Charlie   NaN
   id   name  age
0   1  Alice   20
1   2    Bob   25
2   4    NaN   30

In [53]:
#数据拼接
df3=pd.DataFrame({'id':[1,2,3],'score':[90,85,95]})
concatenated=pd.concat([df1,df3],axis=1)#concat方法用于拼接多个DataFrame对象，参数分别为要拼接的DataFrame对象列表和拼接的轴，这里将df1和df3进行拼接，axis参数设置为1表示按列拼接
print(concatenated)
concatenated=pd.concat([df1,df3],axis=0)#通过设置axis参数为0表示按行拼接
print(concatenated)

   id     name  id  score
0   1    Alice   1     90
1   2      Bob   2     85
2   3  Charlie   3     95
   id     name  score
0   1    Alice    NaN
1   2      Bob    NaN
2   3  Charlie    NaN
0   1      NaN   90.0
1   2      NaN   85.0
2   3      NaN   95.0